In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
import statsmodels.api as sm

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [ ]:
df = pd.read_csv("/content/drive/MyDrive/0.MKCE/Datasets/restaurants.csv")

In [ ]:
X = df['Food_Quality']

Y = df['Price']

In [ ]:
X = sm.add_constant(X)

model = sm.OLS(Y, X).fit()

/usr/local/lib/python3.7/dist-packages/statsmodels/tsa/tsatools.py:117: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  x = pd.concat(x[::order], 1)


In [ ]:
summary = model.summary()
print(summary)

                            OLS Regression Results                            
Dep. Variable:                  Price   R-squared:                       0.321
Model:                            OLS   Adj. R-squared:                  0.300
Method:                 Least Squares   F-statistic:                     15.15
Date:                Thu, 05 May 2022   Prob (F-statistic):           0.000474
Time:                        07:52:27   Log-Likelihood:                -111.50
No. Observations:                  34   AIC:                             227.0
Df Residuals:                      32   BIC:                             230.0
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const          -23.9019     17.718     -1.349   

In [ ]:
sm.stats.linear_rainbow(model)

(3.95352909410105, 0.0051865838644822495)

In [ ]:
model.params

const          -23.901869
Food_Quality     3.249533
dtype: float64

In [ ]:
model.rsquared

0.3212711726017563

In [ ]:
df.columns


Index(['Restaurant_ID', 'Food_Quality', 'Service_Quality', 'Price'], dtype='object')

In [ ]:
df=df.drop(['Restaurant_ID'],axis=1)

In [ ]:
df.columns

Index(['Food_Quality', 'Service_Quality', 'Price'], dtype='object')

In [ ]:
df


Food_Quality  Service_Quality  Price
0             22               20     43
1             20               19     32
2             21               18     34
3             20               17     41
4             24               21     54
5             22               21     52
6             22               21     34
7             20               21     34
8             22               22     39
9             21               19     44
10            19               20     45
11            21               21     47
12            21               20     52
13            19               19     35
14            20               21     47
15            21               21     37
16            22               23     45
17            24               22     57
18            19               18     38
19            22               22     51
20            23               23     54
21            23               21     51
22            20               18     38
23            22               21     49
24            22               22     45
25            19               19     37
26            22               22     50
27            20               18     43
28            22               20     49
29            21               20     65
30            20               18     34
31            21               18     51
32            20               19     49
33            23               23     51

In [ ]:
X=df.drop(['Price'],axis=1)
Y=df['Price']


In [ ]:
X

Food_Quality  Service_Quality
0             22               20
1             20               19
2             21               18
3             20               17
4             24               21
5             22               21
6             22               21
7             20               21
8             22               22
9             21               19
10            19               20
11            21               21
12            21               20
13            19               19
14            20               21
15            21               21
16            22               23
17            24               22
18            19               18
19            22               22
20            23               23
21            23               21
22            20               18
23            22               21
24            22               22
25            19               19
26            22               22
27            20               18
28            22               20
29            21               20
30            20               18
31            21               18
32            20               19
33            23               23

In [ ]:
Y

0     43
1     32
2     34
3     41
4     54
5     52
6     34
7     34
8     39
9     44
10    45
11    47
12    52
13    35
14    47
15    37
16    45
17    57
18    38
19    51
20    54
21    51
22    38
23    49
24    45
25    37
26    50
27    43
28    49
29    65
30    34
31    51
32    49
33    51
Name: Price, dtype: int64

In [ ]:
type(X)

pandas.core.frame.DataFrame

In [ ]:
type(Y)

pandas.core.series.Series

In [ ]:
X=X.values
Y=Y.values

In [ ]:
type(X)

numpy.ndarray

In [ ]:
type(Y)

numpy.ndarray

In [ ]:
import sklearn

In [ ]:
#splitting the dataset into the training set and test set

from sklearn.model_selection import train_test_split
X_training_set,X_testing_set,Y_training_set,Y_testing_set=train_test_split(X,Y,test_size=0.2,random_state=0)

In [ ]:
X_training_set

array([[22, 23],
       [19, 20],
       [23, 23],
       [20, 18],
       [22, 22],
       [21, 21],
       [22, 22],
       [19, 19],
       [22, 20],
       [22, 21],
       [20, 21],
       [21, 20],
       [20, 18],
       [20, 19],
       [21, 20],
       [22, 21],
       [22, 21],
       [24, 21],
       [19, 18],
       [23, 21],
       [22, 22],
       [21, 19],
       [20, 21],
       [20, 19],
       [20, 18],
       [20, 17],
       [22, 20]])

In [ ]:
Y_training_set

array([45, 45, 51, 34, 45, 37, 39, 35, 49, 52, 47, 65, 38, 32, 52, 34, 49,
       54, 38, 51, 51, 44, 34, 49, 43, 41, 43])

In [ ]:
#fitting multiple linear regression to the training set
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_training_set,Y_training_set)

LinearRegression()

In [ ]:
#the coefficients
print('Coefficients:/n',regressor.coef_)

Coefficients:/n [ 2.88046272 -0.04627249]


In [ ]:
regressor.intercept_

-15.435732647814902

In [ ]:
#predicting the test set results
Y_pred=regressor.predict(X_testing_set)
Y_pred

array([44.08226221, 49.75064267, 38.41388175, 52.67737789, 44.22107969,
       46.91645244, 44.22107969])

In [ ]:
# the mean squared error

print("Mean squared error:",sklearn.metrics.mean_squared_error(Y_testing_set,Y_pred))

Mean squared error: 29.598121590148455


In [ ]:
# explained variance score: 1 is prefect prediction

print('Variance score:',sklearn.metrics.r2_score(Y_testing_set,Y_pred))

Variance score: 0.5321587232524921


In [ ]:
# compare actual data with predicted value
import pandas as pd
Y_test=pd.DataFrame(Y_testing_set)
Y_prediction=pd.DataFrame(Y_pred)

comparison=pd.concat([Y_test,Y_prediction],axis=1)
comparison

0          0
0  47  44.082262
1  54  49.750643
2  37  38.413882
3  57  52.677378
4  34  44.221080
5  50  46.916452
6  51  44.221080