In [8]:
#declare a list
import numpy as np
age_list = [23,28,11,18,34]
age_array = np.array(age_list)
print(age_array.ndim)
type(age_array)

1


numpy.ndarray

In [9]:
#declare a list
import numpy as np
age_list = [23,28,11,18,34]
age_array = np.array(age_list)
print(age_array.size)
type(age_array)

5


numpy.ndarray

In [14]:
#declare a list[mean]

import numpy as np
age_list = [23,28,11,18,34]
age_array = np.array(age_list)
print(age_array)
type(age_array)
print(np.mean(age_array,0))

[23 28 11 18 34]
22.8


In [76]:
#strings

import numpy as np
books = np.array(["Learn Python","Data Science Journel","Scale for Data Science"])
print(books)
type(books)
print(books.shape)
print(books.size)
print(books.ndim)
print(books.dtype)

['Learn Python' 'Data Science Journel' 'Scale for Data Science']
(3,)
3
1
<U22


In [40]:
#creating a 1d array of random numbers using random.random()

import numpy as np
np.random.random(size=20)

array([0.4631658 , 0.58742818, 0.1936026 , 0.9839572 , 0.36991475,
       0.51289465, 0.63858521, 0.07175608, 0.37000803, 0.84292058,
       0.39321783, 0.85474912, 0.78543766, 0.50725685, 0.53628668,
       0.01625014, 0.25982385, 0.70452967, 0.47695524, 0.53535001])

In [51]:
#creating a 2d array of random numbers using random.random()

import numpy as np
np.random.rand(2,3)

array([[0.56244955, 0.34574314, 0.42784742],
       [0.60606387, 0.50885876, 0.61733382]])

In [52]:
#creating a 2d array of random numbers using random.random()[normal distribution]

import numpy as np
np.random.randn(2,3)

array([[ 2.21490724, -0.18043642,  0.69769819],
       [-0.7448192 ,  0.87985331,  1.37215929]])

In [84]:
#return integer values in the given range
import numpy as np
a=np.random.randint(2,3)
print(a)


2


In [80]:
#return integer values in the given range 
import numpy as np
a=np.random.randint(10,100,10)
print(a)
print(a.shape)
print(a.size)
print(a.ndim)
print(a.dtype)

[78 87 44 31 45 23 21 67 15 37]
(10,)
10
1
int32


In [79]:
#creating an array of even numbers between given range
import numpy as np
even_num = np.arange(start = 10,stop = 200,step = 100)
print(even_num)
type(even_num)
print(even_num.shape)
print(even_num.size)
print(even_num.ndim)
print(even_num.dtype)

[ 10 110]
(2,)
2
1
int32


In [77]:
#creating numbers between 1 and 100

import numpy as np
nums = np.linspace(start =1,stop =100,num =10)
print(nums)
type(nums)
print(nums.shape)
print(nums.size)
print(nums.ndim)
print(nums.dtype)

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]
(10,)
10
1
float64


In [78]:
#creating 1D numpy array of zeros
import numpy as np
a = np.zeros(10)
print(a)
print(a.ndim)
print(a.size)
print(a.shape)
print(a.dtype)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
1
10
(10,)
float64


In [102]:
#creating 3*3 matrix

import numpy as np
matrix=np.empty((3,3),dtype=int)
print(matrix)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [105]:
#creating 3*3 matrix

import numpy as np
matrix=np.full((3,3),fill_value=11)
print(matrix)

[[11 11 11]
 [11 11 11]
 [11 11 11]]


In [106]:
#identitymatrix
import numpy as np
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [109]:
#np.eye
import numpy as np
np.eye(N = 4,M = 5,k =0)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [117]:
#creating array of name and age of employee

import numpy as np
emp=np.array([("charles",22),("logan",20),("jessica",34)])
print("created_array:",emp)
emp_reshaped=emp.reshape(1,6)
print("Reshaped_array",emp_reshaped)
print(emp_reshaped.ndim)
print("jessi" in emp_reshaped)

created_array: [['charles' '22']
 ['logan' '20']
 ['jessica' '34']]
Reshaped_array [['charles' '22' 'logan' '20' 'jessica' '34']]
2
False


In [120]:
# creating a 1D array [slicing]

import numpy as np
weight = np.array([73,68,55.5,43,92,66])
print("4th and 5th element:",weight[3:5])
print("every second element:",weight[0::3])
print("elements before 43:",weight[:3])


4th and 5th element: [43. 92.]
every second element: [73. 43.]
elements before 43: [73.  68.  55.5]


In [175]:
#example

import numpy as np

weight = np.array([["Ram",50],["krish",70],["siddharth",90],["ram",55],["kannan",50]])
l1=[]
for i in weight:
    l1.append(i[1])
    
minimum=min(l1)
maximum=max(l1)

print("\nminimum weight")
for i in weight:
    if minimum==i[1]:
        print(i)
        
print("\nmaximum weight")
for i in weight:
    if maximum==i[1]:
        print(i)
        



TypeError: 'numpy.ndarray' object is not callable

In [169]:
#example
import numpy as np
weight = np.array([("Ram",50),("krish",70),("siddharth",90),("ram",55),("kannan",50)])
min_w = '0'
for i in weight:
    print("tp1",i[1])
    if min_w>i[1]:
        min=i
        min_w=i[1]
print(min)

tp1 50
tp1 70
tp1 90
tp1 55
tp1 50
['siddharth' '90']


In [155]:
#mean of 2D array

a=np.array([[1,2],[3,4]])
print(a)
print(np.mean(a))
print("dimension",a.ndim)
print("size",a.size)
print("shape",a.shape)

[[1 2]
 [3 4]]
2.5
dimension 2
size 4
shape (2, 2)


In [158]:
#mean of 2D array

a=np.array([[1,2],[3,4]])
print(a)
print("mean",np.mean(a,0))


[[1 2]
 [3 4]]
mean [2. 3.]


In [164]:
#5*5 matrix

import numpy as np
a=np.array([[1,1,1,1,1],[2,2,2,2,2],[3,3,3,3,3],[4,4,4,4,4],[5,5,5,5,5]])
print(a)
print("MEAN",np.mean(a,0)) #if we put (a,0),answer is columnwise orelse (a,0) means answer is rowwise
print("MEAN",np.mean(a,1))

[[1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]
 [5 5 5 5 5]]
MEAN [3. 3. 3. 3. 3.]


In [ ]:
#slicing in 2D array

import numpy as np
age=np.array([(73,68,54),(21,36,19)])
print("Orginal array",age)
print("\nelements from first row and first column:",age[0,0:2])
print("\nelements from first row and first column:",age[0,0:2])

In [2]:
#example

import numpy as np

weight = np.array([("Ram",50),("krish",70),("siddharth",90),("ram",55),("kannan",50)])
l1=[]
for i in weight:
    l1.append(i[1])
    
minimum = min(l1)
maximum = max(l1)

print("\nminimum weight")
for i in weight:
    if minimum == i[1]:
        print(i)
        
print("\nmaximum weight")
for i in weight:
    if maximum == i[1]:
        print(i)


minimum weight
['Ram' '50']
['kannan' '50']

maximum weight
['siddharth' '90']


In [4]:
#consider odd_num and even_num

import numpy as np
odd_num = np.array([3,7,5,9])
even_num = np.array([8,10,4,2])

print("Addition: ",odd_num + even_num)
print("Subtraction: ",odd_num - even_num)


Addition:  [11 17  9 11]
Subtraction:  [-5 -3  1  7]


In [8]:
#multiply

import numpy as np
num=np.array([1,2,3,4,5])
print("Updated_array: ",num*2)


Updated_array:  [ 2  4  6  8 10]


In [13]:
#element wise multiplication in Matrix


import numpy as np
m1 = np.array([[1,0,2],[4,-2,3]])
m2 = np.array([[4,0,1],[2,3,0]])

print("Elementwise Multiplication :\n",m1*m2)

Elementwise Multiplication :
 [[ 4  0  2]
 [ 8 -6  0]]


In [17]:
#multiplication in Matrix using dot() product

import numpy as np
m1 = np.array([[1,0,2],[4,-2,3]])
m2 = np.array([[4,0],[2,3],[1,4]])

print("Matrix Multiplication :\n",m1.dot(m2))

Matrix Multiplication :
 [[ 6  8]
 [15  6]]


In [22]:
#nq.square

import numpy as np
sq_sides = np.array([10,20,30,40,50])
print("square_value:\n",np.power(sq_sides,2))


square_value:
 [ 100  400  900 1600 2500]


In [23]:
#nq.cube

import numpy as np
cube = np.array([10,20,30,40,50])
print("cube_value:\n",np.power(cube,3))


cube_value:
 [  1000   8000  27000  64000 125000]


In [20]:
#transpose matrix

import numpy as np
data_scientists=np.array([("charles",22),("logan",20),("jessica",34)])
print("original matrix:\n",data_scientists)
print("Transpose matrix:\n",np.transpose(data_scientists))


original matrix:
 [['charles' '22']
 ['logan' '20']
 ['jessica' '34']]
Transpose matrix:
 [['charles' 'logan' 'jessica']
 ['22' '20' '34']]


In [24]:
# concatenaion
import numpy as np
age=np.array([19,22,18,20,38,21])
weight=np.array([73,68,55,43,92,66])
print("Concatenated_array:\n",np.concatenate([age,weight]))


Concatenated_array:
 [19 22 18 20 38 21 73 68 55 43 92 66]


In [27]:
#concatenation 2d array

import numpy as np
data_scientists=np.array([("charles",22),("logan",20),("jessica",20)])
consultants=np.array([["Jean",21],["Philips",20]])
print("All_Employees:\n",np.concatenate([data_scientists,consultants]))


All_Employees:
 [['charles' '22']
 ['logan' '20']
 ['jessica' '20']
 ['Jean' '21']
 ['Philips' '20']]
