In [2]:
#Flatend function

import numpy as np
num_array = np.array([[1,3,5,7],[2,4,6,8]])
print("Original array:\n",num_array)
print("Flattend array:\n",np.ndarray.flatten(num_array))

Original array:
 [[1 3 5 7]
 [2 4 6 8]]
Flattend array:
 [1 3 5 7 2 4 6 8]


In [5]:
#Iteration for 1D array

books = np.array(["Data Science with Python","Machines are Learning","DIY - Deep Learning"])
print("The array 'books' is", books.ndim , "dimensional array\n")
for i in books:
    print(i)

The array 'books' is 1 dimensional array

Data Science with Python
Machines are Learning
DIY - Deep Learning


In [6]:
#Iteration for 2D array

books = np.array([["Data Science with Python","Machines are Learning","DIY - Deep Learning"]])
print("The array 'books' is", books.ndim , "dimensional array\n")
for i in books:
    print(i)

The array 'books' is 2 dimensional array

['Data Science with Python' 'Machines are Learning' 'DIY - Deep Learning']


In [8]:
#Iteration for 2D array

books = np.array([["Data Science with Python","Machines are Learning","DIY - Deep Learning"]])
print("The array 'books' is", books.ndim , "dimensional array\n")
for i in books:
    for j in i:
        print(j)
    

The array 'books' is 2 dimensional array

Data Science with Python
Machines are Learning
DIY - Deep Learning


In [11]:
#importing required library

import numpy
import time

size = 1000000

num_list1 = range(size)
num_list2 = range(size)

initialTime = time.time()
resultant_list = [(a*b) for a,b in zip(num_list1,num_list2)]

print("Time Taken by lists :",(time.time() - initialTime),"Seconds")


Time Taken by lists : 0.21642160415649414 Seconds


In [18]:
#calculating time


num_array1 = numpy.arange(size)
num_array2 = numpy.arange(size)

initialTime = time.time()
resultant_array = num_array1 * num_array2

print("Time Taken by lists :",(time.time() - initialTime),"Seconds")


Time Taken by lists : 0.0049877166748046875 Seconds


In [36]:
#Mean for row and column wise

import numpy as np

temp_9am = np.array([32,32,32,31,31,31,31])
temp_6pm = np.array([36,36,36,36,36,36,35])

initialTime = time.time()
print("Mean temp_9am:\n",np.mean(temp_9am),"\n")
print("Mean temp_6pm:\n",np.mean(temp_6pm),"\n")
print("Mean for both Column-wise:\n",(temp_9am + temp_6pm)/2,"\n")
print("Mean for both:\n",np.mean(temp_9am + temp_6pm)/2,"\n")
print("Time Taken for completion:\n",(time.time() - initialTime),"Seconds")



Mean temp_9am:
 31.428571428571427 0 

Mean temp_6pm:
 35.857142857142854 

Mean for both Column-wise:
 [34.  34.  34.  33.5 33.5 33.5 33. ] 

Mean for both:
 33.642857142857146 

Time Taken for completion:
 0.0029938220977783203 Seconds


In [51]:
#using def()function
#Mean for row and column wise

import numpy as np

def mean_temp(temp_9am_6pm):
    
    m_1=np.mean(temp_9am_6pm)
    m_2=np.mean(temp_9am_6pm,0)
    m_3=np.mean(temp_9am_6pm,1)
    
    return m_1,m_2,m_3


temp_9am_6pm = np.array([(32,36),(32,36),(32,36),(31,36),(31,36),(31,36),(31,35)])
m_1,m_2,m_3 = mean_temp(temp_9am_6pm)

initialTime = time.time()

print("Total_mean",m_1)
print("Column_mean",m_2)
#print("Column_mean",np.mean(m_2))
print("Row_mean",m_3)
#print("Row_mean",np.mean(m_3))


print("Time Taken for completion:\n",(time.time() - initialTime),"Seconds")




Total_mean 33.642857142857146
Column_mean [31.42857143 35.85714286]
Row_mean [34.  34.  34.  33.5 33.5 33.5 33. ]
Time Taken for completion:
 0.0029900074005126953 Seconds


In [49]:
#import reduce function

from functools import reduce
num_list = [1,2,3,4,5]
reduce(lambda a,b: a*b,num_list)

120

In [71]:
#minimum of numeric tuple
import time
from functools import reduce
initialTime = time.time()
num_tup  = (0,-8,-100,1000,33)
print(reduce(lambda x,y: x if (x<y) else y,num_tup))
print("Time Taken for completion:\n",(time.time() - initialTime),"Seconds")

-100
Time Taken for completion:
 0.0009996891021728516 Seconds


In [76]:
import time

initialTime = time.time()
num_tup  = (0,-8,-100,1000,33)
print(min(num_tup))
print("Time Taken for completion:\n",(time.time() - initialTime),"Seconds")

-100
Time Taken for completion:
 0.0009965896606445312 Seconds


In [78]:
import time
num_tup  = (0,-8,-100,1000,33)
initialTime = time.time()
a=num_tup[0]
for i in num_tup:
    if a>i:
        a=i
print(a)
print("Time Taken for completion:\n",(time.time() - initialTime),"Seconds")

-100
Time Taken for completion:
 0.001995563507080078 Seconds


In [67]:
from functools import reduce
import time
num=[0.0009970664978027344, 0.0009980201721191406, 0.001001119613647461]
initialTime=time.time()
print(reduce(lambda x,y: x if(x<y) else y,num))
print("Time Taken for completion:\n",(time.time() - initialTime),"Seconds")


0.0009970664978027344
Time Taken for completion:
 0.0009946823120117188 Seconds


In [82]:
#3D

import numpy as np
array_example = np.array([[[0,1,2,3],[4,5,6,7]],[[0,1,2,3],[4,5,6,7]],[[0,1,2,3],[4,5,6,7]]])
print(array_example)
print(np.shape(array_example))
print(np.size(array_example))
print(np.ndim(array_example))

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]
(3, 2, 4)
24
3


In [99]:
#3D

import numpy as np
example=np.array([[[0,1],[4,5]],[[0,1],[4,5]],[[0,1],[4,5]]])
print(example)
print("SIZE:\n",np.size(example))
print("DIMENSION:\n",np.ndim(example),"\n")
print('0(MEAN At the 0th position)\n',np.mean(example,0)) #mean at '0'th axis
print('1\n',np.mean(example,1))  #mean at '1'st axis
print('2\n',np.mean(example,2))   #mean at '2'nd axis

[[[0 1]
  [4 5]]

 [[0 1]
  [4 5]]

 [[0 1]
  [4 5]]]
SIZE:
 12
DIMENSION:
 3 

0(MEAN At the 0th position)
 [[0. 1.]
 [4. 5.]]
1
 [[2. 3.]
 [2. 3.]
 [2. 3.]]
2
 [[0.5 4.5]
 [0.5 4.5]
 [0.5 4.5]]


In [96]:

import numpy as np
example=np.array([[[0,1],[4,5]],[[2,4],[6,8]],[[3,2],[5,1]]])
print(example)
print("SIZE:\n",np.size(example))
print("DIMENSION:\n",np.ndim(example),"\n")
#print('0\n',np.mean(example,0)) #mean at '0'th axis
print('1st axis mean(Column)\n',np.mean(example,1))  #mean at '1'st axis
#print('2\n',np.mean(example,2))   #mean at '2'nd axis

[[[0 1]
  [4 5]]

 [[2 4]
  [6 8]]

 [[3 2]
  [5 1]]]
SIZE:
 12
DIMENSION:
 3 

1st axis mean(Column)
 [[2.  3. ]
 [4.  6. ]
 [4.  1.5]]


In [95]:
import numpy as np
example=np.array([[[0,1],[4,5]],[[2,4],[6,8]],[[3,2],[5,1]]])
print(example)
print("SIZE:\n",np.size(example))
print("DIMENSION:\n",np.ndim(example),"\n")
#print('0\n',np.mean(example,0)) #mean at '0'th axis
#print('1st axis mean(Column)\n',np.mean(example,1))  #mean at '1'st axis(Column-wise)
print('2nd axis mean(Row)\n',np.mean(example,2))   #mean at '2'nd axis(Row-wise)

[[[0 1]
  [4 5]]

 [[2 4]
  [6 8]]

 [[3 2]
  [5 1]]]
SIZE:
 12
DIMENSION:
 3 

2nd axis mean(Row)
 [[0.5 4.5]
 [3.  7. ]
 [2.5 3. ]]


In [106]:
#3D vera_level example

import numpy as np
array_example = np.array([[[0,1,2,3],[4,5,6,7]],[[0,1,2,3],[4,5,6,7]],[[0,1,2,3],[4,5,6,7]]])
print(array_example)
print("SHAPE:\n",np.shape(array_example))
print("SIZE:\n",np.size(array_example))
print("DIMENSION:\n",np.ndim(array_example))
print("TOTAL_MEAN:\n",np.mean(array_example))
print("0th axis_Mean:\n",np.mean(array_example,0))
print("Column-wise_Mean:\n",np.mean(array_example,1))
print("Row-wise_Mean:\n",np.mean(array_example,2))

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]
SHAPE:
 (3, 2, 4)
SIZE:
 24
DIMENSION:
 3
TOTAL_MEAN:
 3.5
0th axis_Mean:
 [[0. 1. 2. 3.]
 [4. 5. 6. 7.]]
Column-wise_Mean:
 [[2. 3. 4. 5.]
 [2. 3. 4. 5.]
 [2. 3. 4. 5.]]
Row-wise_Mean:
 [[1.5 5.5]
 [1.5 5.5]
 [1.5 5.5]]


In [111]:
#2D operation

import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print("1st:\n",a[1:,:2]) #(2,2)
print("2nd:\n",a[1:2,:])#(3,)(1,3)
print("3rd:\n",a[0:1,1:])#(2,)(1,2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1st:
 [[4 5]
 [7 8]]
2nd:
 [[4 5 6]]
3rd:
 [[2 3]]
